### ISSUE TITLE
Doesn't work with PNG

### ISSUE THREAD

**Issue by cauli** [leesherwood/Orientation-Fix-PHP#1]
Apparently read_exif_data on line 33 of fix_orientation only supports JPEG and TIFF

**Comment by leesherwood** [comment]
This was thrown together very quickly to help someone over at StackOverflow, so i must admit that not only is it quite old, it's also unmaintained and was not intended to cover everything. Having said that, i'm happy to add/edit to help people out where i can.

As far as i'm aware, PNG's don't support EXIF data. They support some form of metadata embedded in the image, but looking at: http://en.wikipedia.org/wiki/Portable_Network_Graphics#Ancillary_chunks that doesn't include orientation.

Worth noting that the code provided is intended to help standardise the orientation of pictures taken with a camera (photos), not to magically work out the orientation of something you drew in a graphics program or found on google images. Camera's don't tend to save to PNG file format (because camera makers dont want to lose the ability to provide rich contextual information about photos in exif, and PNG sits in the "pointless land" between jpeg and "RAW").

**Comment by cauli** [comment]
That's what I was supposed later on.

The code is old but it still works and helped me a lot, so thank you.

Thanks for the info!
